### ISSUE TITLE
Aproval/publishing the Name space Register under the SK Registry

### ISSUE THREAD

**Issue by MartinTuchyna** [ec-jrc/re3gistry#13]
I have created the new item under the SK Registy called Namespace Register
(https://inspire-sandbox.jrc.ec.europa.eu/re3gistry2/browse?itemUuid=681f2922a15b5dbf5c10efc99a1fdd4e&languageUuid=en). 
System is indicated status draft.
Where I can aprove/publish this register?
Thanks, Martin

**Comment by df-git** [comment]
Dear Martin,
Thank you for your question. This will be more clear when the publication workflow will be available in the User guide.

The item you created is in the "draft" status because you proposed it but it has not yet undergone the approval workflow.
To publish it, you need to follow the workflow to publish it:
- You need to go to the "Submitting Organization" and "Submit to Control Body".
- The Control Body needs to take a decision on it (your user it is registry manger, so you can access alto the Control Body tab and approve it).
- The "Register Manager" or "Registry manager" has to "Publish" it.

**Comment by MartinTuchyna** [comment]
Thanks, based on this guidance, seems I managed to aprove and publish it.
