### ISSUE TITLE
Error 503 when asking for other encodings

### ISSUE THREAD

**Issue by marcingrudzien** [ec-jrc/re3gistry#149]
Hi,

I have noticed one more issue with the frontend app. When I want to display the data in any encoding other than default HTML (e.g. XML Registry, XML ISO 19135, RDF/XML, etc.) using forntend GUI after waiting 2 minutes I receive an error 503. See details below.
![image](https://user-images.githubusercontent.com/25637709/169001273-a2243120-0ffc-4609-b8b1-802565e6afd2.png)

Can it be fixed?

Best regards,
Marcin

**Comment by oscar9** [comment]
Hi @marcingrudzien ,

I'm trying to replicate the error in a local instance and right know I'm not able to. Please, can you confirm witch of all these url are not working? Also be sure that you press Control+F5 in the navigator to ensure that you are refreshing the cache correctly and not looking to an old frontend. At first look it looks like some part of your services stopped working.

According to your url, check:
registry.geoportal.gov.pl/registry/gugik/INSPIRE/codelist/LandCoverClassValue/LandCoverClassValue
registry.geoportal.gov.pl/registry/gugik/INSPIRE/codelist/LandCoverClassValue/LandCoverClassValue.pl.iso19135xml
registry.geoportal.gov.pl/registry/gugik/INSPIRE/codelist/LandCoverClassValue/LandCoverClassValue.pl.xml
registry.geoportal.gov.pl/registry/gugik/INSPIRE/codelist/LandCoverClassValue/LandCoverClassValue.pl.rdf
registry.geoportal.gov.pl/registry/gugik/INSPIRE/codelist/LandCoverClassValue/LandCoverClassValue.pl.json

Can you confirm that you can navigate through your frontend and it just fails with that error when you click on that format?
Also, if you are able to, check in the log if the tomcat/postgres/httpd are giving any error.

We will be doing our analysis and keep you informed. Thanks for reporting the issue.

**Comment by marcingrudzien** [comment]
Hi @oscar9 

Thank you for your support.

All URLs are not working. However, the first URL returns the website with error. Analysis of the error shows that the frontend app wants to access http://registry.geoportal.gov.pl/registry/rest?uri=http%3A%2F%2Fregistry.geoportal.gov.pl%2Fregistry%2Fgugik%2FINSPIRE%2Fcodelist%2FLandCoverClassValue%2FLandCoverClassValue&lang=pl&format=jsonc and this returns 404.
Other URLs from your list return 503. 

However, if I change the request to IP address instead of domain e.g. http://192.168.103.3/registry/gugik/INSPIRE/codelist/LandCoverClassValue/LandCoverClassValue.pl.xml I get 
```
{
  "error" : {
    "code" : 404,
    "description" : "Element not found",
    "description-code" : "not-found"
  }
}
```


Control+F5 doesn't help. Moreover, I am testing using ChromeDev tools with the enabled option _Disable cache_.

I confirm that I can navigate through the fronted. The corresponding URL that works fine is http://registry.geoportal.gov.pl/registry/gugik/INSPIRE/codelist/LandCoverClassValue 

Apache error log shows for example at the end of the file

```
[Thu May 19 10:26:45.840226 2022] [proxy_http:error] [pid 2509003:tid 140718966306560] [client 192.168.103.4:60348] AH01114: HTTP: failed to make connection to backend: registry.geoportal.gov.pl
[Thu May 19 10:26:47.892065 2022] [proxy:error] [pid 2509004:tid 140718362326784] (110)Connection timed out: AH00957: http: attempt to connect to 192.168.202.78:80 (*) failed
[Thu May 19 10:26:47.892137 2022] [proxy_http:error] [pid 2509004:tid 140718362326784] [client 192.168.103.4:62620] AH01114: HTTP: failed to make connection to backend: registry.geoportal.gov.pl
[Thu May 19 10:32:27.856208 2022] [proxy:error] [pid 2509004:tid 140718848841472] (110)Connection timed out: AH00957: http: attempt to connect to 192.168.202.78:80 (*) failed
[Thu May 19 10:32:27.856370 2022] [proxy_http:error] [pid 2509004:tid 140718848841472] [client 192.168.103.4:62937] AH01114: HTTP: failed to make connection to backend: registry.geoportal.gov.pl
[Thu May 19 10:32:34.000185 2022] [proxy:error] [pid 2509003:tid 140719830329088] (110)Connection timed out: AH00957: http: attempt to connect to 192.168.202.78:80 (*) failed
[Thu May 19 10:32:34.000306 2022] [proxy_http:error] [pid 2509003:tid 140719830329088] [client 192.168.103.4:62940] AH01114: HTTP: failed to make connection to backend: registry.geoportal.gov.pl
```
According to the log Apache tries to connect to 192.168.202.78:80. Do you think it is a problem with the frontend application or 
maybe network configuration on our side?

Best regards,
Marcin

**Comment by oscar9** [comment]
Just to clarify, you can navigate through the frontend and see this value shown in the web:
(link 1) http://registry.geoportal.gov.pl/registry/gugik/INSPIRE/codelist/LandCoverClassValue

But if you click to the format XML for example, i suppose it will try to redirect you to this link and it fails
(link 2) http://registry.geoportal.gov.pl/registry/gugik/INSPIRE/codelist/LandCoverClassValue/LandCoverClassValue.pl.xml

What is this responding? a json or a html error? a timeout error?


I assume that this url its showing a json with a 406 error but it's working
(link 3) http://registry.geoportal.gov.pl/registry/rest?

You said that the frontend tries to access to this url: 
(link 4) http://registry.geoportal.gov.pl/registry/rest?uri=http://registry.geoportal.gov.pl/registry/gugik/INSPIRE/codelist/LandCoverClassValue/LandCoverClassValue&lang=pl&format=jsonc

But that one it is not the correct uri. I has an extra "LandCoverClassValue". I think it should be like this one (link 5).
(link 5) 
http://registry.geoportal.gov.pl/registry/rest?uri=http://registry.geoportal.gov.pl/registry/gugik/INSPIRE/codelist/LandCoverClassValue&lang=pl&format=jsonc
Can you check if this link 5 works for you? (it should return a valid json finding the value that you navigated through the frontend)


This link probably it should't work (link 6) becouse you have a configuration to be use with the other name registry.geoportal.gov.pl (link 7)
(link 6) http://192.168.103.3/registry/gugik/INSPIRE/codelist/LandCoverClassValue/LandCoverClassValue.pl.xml

(link 7) http://registry.geoportal.gov.pl/registry/gugik/INSPIRE/codelist/LandCoverClassValue/LandCoverClassValue.pl.xml

Sorry maybe I'm supposing wrong some of your URLs.

But again, I'm not sure what the problem is. It looks like the httpd it's not doing correctly the petitions, maybe they are not configured correctly in the httpd.conf or some of this petition cause the service to crash and that's why it is giving you the Unavailable service error. The port:80 is related to the virtual host of the apache httpd.

Let us know any finding you make. I will keep trying to solve your issue.

**Comment by arantzaetxebarria** [comment]
Due to the user's lack of response, the issue has been closed.
Please don't hesitate to contact us if you encounter any new problems.

Regards
