### ISSUE TITLE
Question on code in ItemsServlet

### ISSUE THREAD

**Issue by heidivanparys** [ec-jrc/re3gistry#87]
Why is the following code needed?

https://github.com/ec-jrc/re3gistry/blob/79f806053066cfa1fb1636ce34b64912004ccb32/sources/Re3gistry2RestAPI/src/main/java/eu/europa/ec/re3gistry2/restapi/ItemsServlet.java#L105-L114

It seems unnecessary, and it gave me an error, as I had a URI of the following form:

```
https://10.<rest_of_IP_address/mylist/10",
```

which the REST API then shortened to 

```
https://10.<rest_of_IP_address/mylist",
```

instead of keeping the URI as it was.

**Comment by emanuelaepure10** [comment]
Dear @heidivanparys 

I see the error. For you any however has the same localID twice in the uri cannot work.
For us it was working twice the localId in the uri...but this could happened in our case just when calling .../localId/localId.format.language
but I dont see anymore the case...because is calling anyway the api.
Feel free to remove it
Best regards,
